### PR TITLE
One page per success criterion

### PR DESCRIPTION
**Pull request by andrewhick**
This PR covers the remaining structural changes suggested by @selfthinker so that there is a single page per success criterion. The changes are:

- Rename the `documentation` folder to `sc`
- Update the config file so that header links begin with `/` to ensure that the links will go to the correct destination
- Update the partials in the `all`, `code`, `content` and `design` pages to link to the new pages instead
- Update the success criterion links in the `index` page to go to the new pages (rather than the relevant section of the `all` page)
- Rename each success criterion page from `*.md` to `*.html.md.erb`
- Add a meaningful `title` to every success criterion page
- Restructure the headings on every success criterion page so that they start with `<h1>`
- Separate out the link to each understanding page, making the links go to a consistent destination
- Add A/AA to the links from the `all`, `code`, `content` and `design` pages
- Make capitalisation consistent for each success criterion

I have tested all links on the `index` and `all` pages, and spot checked others where they are repeated. Everything appears to be working.

### CODE REVIEW

**Comment by selfthinker** [comment]
@andrewhick, as discussed, I cleaned the commit history up a bit. The only content change I've made is that I changed all the links that went to the WCAG 2.0 version of an Understanding document to the WCAG 2.1 version.

And at the end I've added an unrelated fix that I've noticed. (I could also make a separate PR for it.)

Could you review my changes and that everything works for you? When it does, I'm happy to approve the PR.

**Comment by selfthinker** [comment]
Before we merge this, we should also consider that most of the URLs will change. That might be worth telling people about. I don't think any of the previous URLs will stop working, except the anchors.

**Comment by andrewhick** [comment]
Thanks @selfthinker , I've run it locally and found no issues. In particular, I've:

- retested all of the success criterion (SC) links from the `index` and `all` pages
- spot checked links from the `content`, `design` and `code` pages
- tested all the links to the WCAG 2.1 understanding pages from each SC page
- checked the `3.1.1` page
- reviewed the diff for the whole PR again

Personally I'm not too worried about links changing because the top-level pages are unchanged, and selecting an incorrect anchor link will simply send people to the top of the `all` page. But I'm happy to discuss further.

**Comment by andrewhick** [comment]
We also discussed moving the success criteria links into lists, so I also made that change and updated the capitalisation for the guidelines while I was there.

**Comment by selfthinker** [comment]
Thanks @andrewhick. I've checked the latest changes again. I think it's good to go. 👍

**Comment by andrewhick** [comment]
Thanks, as discussed I've made one final tweak to the capitalisation that was incorrect. I'll merge shortly.

**Pull request merged**
